name: Build & Test (Clang)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test-clang:
    runs-on: ubuntu-latest

    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Tools
      run: |
        sudo apt update
        sudo apt install -y ninja-build cmake
        sudo apt install -y wget gnupg lsb-release software-properties-common

    - name: Add LLVM apt repository (for Clang 22)
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 22
        sudo apt install -y libc++-22-dev libc++abi-22-dev

    - name: Set Clang 22 as default
      run: |
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-22 110
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-22 110
        clang --version
        clang++ --version

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git $VCPKG_ROOT
        $VCPKG_ROOT/bootstrap-vcpkg.sh

    - name: Configure with CMake Preset
      run: cmake --preset x64-linux-clang-dynamic

    - name: Print vcpkg log to the console
      if: failure()
      run: |
        echo "CMake Configuration failed. Printing vcpkg logs:"
        cat /home/runner/work/whisp/whisp/vcpkg/buildtrees/detect_compiler/stdout-x64-linux-clang-dynamic.log || echo "Log not found"
        cat /home/runner/work/whisp/whisp/vcpkg/buildtrees/detect_compiler/config-x64-linux-clang-dynamic-rel-out.log || echo "Log not found"
        cat /home/runner/work/whisp/whisp/vcpkg/buildtrees/detect_compiler/config-x64-linux-clang-dynamic-rel-err.log || echo "Log not found"

    - name: Build unit tests
      run: cmake --build --preset x64-linux-clang-dynamic --config Release --target tests

    - name: Run unit tests
      run: ctest --preset x64-linux-clang-dynamic --build-config Release
