name: Build & Test (GCC)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test-gcc:
    runs-on: ubuntu-latest

    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Tools
      run: sudo apt-get update && sudo apt-get install -y ninja-build cmake

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git $VCPKG_ROOT
        $VCPKG_ROOT/bootstrap-vcpkg.sh

    - name: Configure with CMake Preset
      run: cmake --preset x64-linux-gcc-dynamic

    - name: Build unit tests
      run: cmake --build --preset x64-linux-gcc-dynamic --config Release --target whisp_tests

    - name: Run unit tests
      run: ctest --preset x64-linux-gcc-dynamic --build-config Release
